"""Load and validate the compiled survey spec.

``data/msat_spec.json`` is generated by ``scripts/compile_script.py`` from the
document transcription plus the one hand-authored artefact, ``data/slot_map.json``.
Nothing in the runtime hard-codes a question, an answer option, a slot, a
condition or a payload key: it all comes from here, and every turn carries the
node id it was transcribed under.

Validation happens at load, once, and fails loudly. The rule this file exists to
enforce is that a survey cannot be *slightly* wrong: a question whose printed
options no longer match the options the agent will accept, or a conditional
question that depends on an answer the call has not reached yet, is a call that
records plausible-looking data nobody can trust.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from enum import StrEnum
from functools import lru_cache
from pathlib import Path
from typing import Any, Callable

DATA_DIR = Path(__file__).resolve().parents[2] / "data"
SPEC_FILE = DATA_DIR / "msat_spec.json"
INPUT_SCHEMA_FILE = DATA_DIR / "input_schema.json"

# Turn kinds the agent speaks. Anything else is printed in the document but never
# said out loud — routing rules and the key at the foot of the script.
AGENT_KINDS = frozenset(
    {
        "voicemail",
        "intro",
        "consent",
        "reschedule_offer",
        "reschedule_transfer",
        "uninterested_close",
        "survey_intro",
        "ask",
        "close",
    }
)
# Kinds the call cannot be run without, each appearing exactly once.
SINGLETON_KINDS = AGENT_KINDS - {"ask"}

# Off-script lines the runtime will ask for by name. Declared here so a missing
# one fails the build rather than the call that needs it — and the call that
# needs `safeguarding_handoff` is the worst possible one to discover it on.
REQUIRED_LINES = frozenset(
    {
        "policyholder_unavailable",
        "wrong_number",
        "do_not_call",
        "hold_ack",
        "unnamed_policyholder",
        "side_request_ack",
        "unable_to_continue",
        "representative_handoff",
        "safeguarding_handoff",
    }
)

# Lines whose wording is a commitment to the member, not a courtesy. These say
# what is about to happen to them; an agent paraphrasing "someone will join the
# call" into something vaguer is a promise quietly withdrawn.
VERBATIM_ONLY_LINES = frozenset({"safeguarding_handoff", "representative_handoff", "do_not_call"})


class SlotType(StrEnum):
    YES_NO = "yes_no"
    CHOICE = "choice"
    # A survey free-text answer, where "no" and "none" are answers rather than
    # refusals — the document says so in the question itself.
    FEEDBACK_TEXT = "feedback_text"
    PERSON_NAME = "person_name"


class SpecError(ValueError):
    """The committed spec is not self-consistent. Always names the offender."""


@dataclass(frozen=True)
class Option:
    """One printed answer option, and the value it is recorded as."""

    value: str
    label: str
    synonyms: tuple[str, ...] = ()

    @property
    def phrases(self) -> tuple[str, ...]:
        """Everything a member could say that means this option."""
        return (self.label, self.value.replace("_", " "), *self.synonyms)


@dataclass(frozen=True)
class SlotSpec:
    name: str
    type: SlotType
    critical: bool
    description: str
    options: tuple[Option, ...] = ()
    # Supplied by the work item and never asked for. The risk tier is the only
    # one: it decides whether question 5 is put, and no answer on the call may
    # change it.
    payload_only: bool = False

    def option(self, value: str) -> Option | None:
        return next((option for option in self.options if option.value == value), None)

    @property
    def option_values(self) -> tuple[str, ...]:
        return tuple(option.value for option in self.options)

    @property
    def option_labels(self) -> tuple[str, ...]:
        return tuple(option.label for option in self.options)


@dataclass(frozen=True)
class Condition:
    """When a question applies. Absent means always.

    Two sources, and the difference matters. ``answer`` reads something the
    member has already told us on this call; ``payload`` reads something the work
    item brought with it. Question 5 is gated on the payload, so a member cannot
    talk their way into or out of it, and a work item that does not say cannot
    have it guessed.
    """

    source: str  # "answer" | "payload"
    slot: str
    equals: str = ""
    accepted: tuple[str, ...] = ()

    def holds(self, *, answers: dict[str, str], payload_lookup: Callable[[str], str]) -> bool:
        value = (answers.get(self.slot, "") if self.source == "answer" else payload_lookup(self.slot)) or ""
        if self.equals:
            return value == self.equals
        return value in self.accepted

    def describe(self) -> str:
        wanted = self.equals or " or ".join(self.accepted)
        return f"{self.source} {self.slot} is not {wanted}"


@dataclass(frozen=True)
class Turn:
    node: str
    section: str
    role: str
    kind: str
    text: str
    goal: str = ""
    number: str = ""
    slots: tuple[str, ...] = ()
    # Values this turn speaks from the work item rather than asking for: the
    # policyholder's name in the introduction, and nothing else.
    payload_slots: tuple[str, ...] = ()
    options: tuple[str, ...] = ()
    when: Condition | None = None
    # The document's printed wording is wrong for this turn and the goal is
    # right. Set on exactly one turn — see the source note on 1b.
    speak_goal_not_text: bool = False
    source_note: tuple[str, ...] = ()

    @property
    def slot(self) -> str:
        return self.slots[0] if self.slots else ""


@dataclass(frozen=True)
class PayloadBinding:
    slot: str
    paths: tuple[str, ...]
    compose: tuple[str, ...] = ()


@dataclass(frozen=True)
class SpokenLine:
    """A line the agent can say that the document does not contain.

    ``goal`` empty means the line is spoken exactly as written — the normal case,
    because these are approved wording. A goal makes it an *intent* instead: the
    agent says it in its own words with the line as the reference. That is right
    for a courtesy said over and over ("take your time"), where hearing the same
    sentence every time is itself a message, and wrong for anything approved for
    what it says.
    """

    name: str
    line: str
    goal: str = ""

    @property
    def verbatim(self) -> bool:
        return not self.goal


@dataclass(frozen=True)
class CallPolicy:
    """Thresholds and the lines that are not in the document.

    ``off_script`` is deliberately data. Every line the agent can say that the
    PDF does not contain is listed in one place a reviewer can read, rather than
    scattered through Python as string constants nobody outside the codebase
    will ever see.
    """

    max_asks_per_slot: int
    max_consecutive_holds: int
    max_identity_asks: int
    max_consent_asks: int
    off_script: dict[str, SpokenLine] = field(default_factory=dict)

    def spoken(self, name: str) -> SpokenLine:
        try:
            return self.off_script[name]
        except KeyError as exc:
            raise SpecError(
                f"no off-script line named {name!r}; slot_map.json declares {sorted(self.off_script)}"
            ) from exc

    def line(self, name: str) -> str:
        return self.spoken(name).line


@dataclass(frozen=True)
class SurveySpec:
    source: dict[str, Any]
    turns: tuple[Turn, ...]
    slots: dict[str, SlotSpec]
    payload: dict[str, PayloadBinding]
    policy: CallPolicy

    # ── turns ────────────────────────────────────────────────────────────

    def turn(self, node: str) -> Turn | None:
        return next((turn for turn in self.turns if turn.node == node), None)

    def of_kind(self, kind: str) -> Turn:
        """The single turn of ``kind``. Validated at load, so this cannot miss."""
        turn = next((turn for turn in self.turns if turn.kind == kind), None)
        if turn is None:  # pragma: no cover - _validate_required_kinds fires first
            raise SpecError(f"the script has no {kind!r} turn")
        return turn

    @property
    def questions(self) -> tuple[Turn, ...]:
        """The survey's questions, in the order the document prints them."""
        return tuple(turn for turn in self.turns if turn.kind == "ask")

    @property
    def agent_turns(self) -> tuple[Turn, ...]:
        return tuple(turn for turn in self.turns if turn.role == "agent")

    def question_for(self, slot: str) -> Turn | None:
        return next((turn for turn in self.questions if slot in turn.slots), None)

    # ── slots ────────────────────────────────────────────────────────────

    def slot(self, name: str) -> SlotSpec:
        try:
            return self.slots[name]
        except KeyError as exc:
            raise SpecError(f"unknown slot {name!r}; the script declares {sorted(self.slots)}") from exc

    @property
    def question_slots(self) -> tuple[str, ...]:
        """Slots the survey asks for, in question order."""
        seen: list[str] = []
        for turn in self.questions:
            for slot in turn.slots:
                if slot not in seen:
                    seen.append(slot)
        return tuple(seen)

    @property
    def critical_slots(self) -> frozenset[str]:
        return frozenset(name for name, spec in self.slots.items() if spec.critical)

    @property
    def payload_only_slots(self) -> tuple[str, ...]:
        return tuple(name for name, spec in self.slots.items() if spec.payload_only)

    @property
    def condition_payload_slots(self) -> tuple[str, ...]:
        """Work-item facts that decide which questions this member is asked.

        Reported in the call outcome so a reader can see why a question was or
        was not put without going back to the work item.
        """
        return tuple(
            dict.fromkeys(
                turn.when.slot
                for turn in self.questions
                if turn.when is not None and turn.when.source == "payload"
            )
        )

    def all_slots(self) -> frozenset[str]:
        return frozenset(slot for turn in self.turns for slot in turn.slots)


# ── parsing ──────────────────────────────────────────────────────────────


def _condition(slot_owner: str, raw: dict | None) -> Condition | None:
    if not raw:
        return None
    if len(raw) != 1:
        raise SpecError(
            f"turn {slot_owner!r} declares a condition with {sorted(raw)}; expected exactly one source"
        )
    source, body = next(iter(raw.items()))
    if source not in ("answer", "payload"):
        raise SpecError(
            f"turn {slot_owner!r} has unknown condition source {source!r}; use 'answer' or 'payload'"
        )
    if not isinstance(body, dict) or "slot" not in body:
        raise SpecError(f"turn {slot_owner!r} condition names no slot")
    equals = str(body.get("equals") or "")
    accepted = tuple(str(item) for item in body.get("in") or ())
    if not equals and not accepted:
        raise SpecError(
            f"turn {slot_owner!r} condition on {body['slot']!r} declares neither 'equals' nor 'in'"
        )
    if equals and accepted:
        raise SpecError(f"turn {slot_owner!r} condition on {body['slot']!r} declares both 'equals' and 'in'")
    return Condition(source=source, slot=str(body["slot"]), equals=equals, accepted=accepted)


def _turn(raw: dict) -> Turn:
    for field_name in ("node", "role", "kind", "text"):
        if not str(raw.get(field_name) or "").strip():
            raise SpecError(f"a turn is missing {field_name!r}: {raw!r}")
    return Turn(
        node=raw["node"],
        section=raw.get("section", ""),
        role=raw["role"],
        kind=raw["kind"],
        text=raw["text"],
        goal=raw.get("goal", ""),
        number=str(raw.get("number") or ""),
        slots=tuple(raw.get("slots") or ()),
        payload_slots=tuple(raw.get("payload_slots") or ()),
        options=tuple(raw.get("options") or ()),
        when=_condition(raw["node"], raw.get("when")),
        speak_goal_not_text=bool(raw.get("speak_goal_not_text", False)),
        source_note=tuple(raw.get("source_note") or ()),
    )


def _option(slot: str, raw: dict) -> Option:
    for field_name in ("value", "label"):
        if not str(raw.get(field_name) or "").strip():
            raise SpecError(f"slot {slot!r} has an option missing {field_name!r}")
    return Option(
        value=raw["value"],
        label=raw["label"],
        synonyms=tuple(raw.get("synonyms") or ()),
    )


def _slot_spec(name: str, raw: dict) -> SlotSpec:
    for field_name in ("type", "critical", "description"):
        if field_name not in raw:
            raise SpecError(f"slot {name!r} is missing {field_name!r}")
    try:
        kind = SlotType(raw["type"])
    except ValueError as exc:
        raise SpecError(
            f"slot {name!r} has unknown type {raw['type']!r}; "
            f"known types are {sorted(t.value for t in SlotType)}"
        ) from exc
    if not isinstance(raw["critical"], bool):
        raise SpecError(f"slot {name!r} 'critical' must be true or false")
    if not str(raw["description"]).strip():
        raise SpecError(f"slot {name!r} has an empty description; the extractor needs one line")
    return SlotSpec(
        name=name,
        type=kind,
        critical=raw["critical"],
        description=raw["description"],
        options=tuple(_option(name, item) for item in raw.get("options") or ()),
        payload_only=bool(raw.get("payload_only", False)),
    )


def _payload_binding(slot: str, raw: dict) -> PayloadBinding:
    paths = tuple(raw.get("paths") or ())
    compose = tuple(raw.get("compose") or ())
    if not paths and not compose:
        raise SpecError(f"payload binding {slot!r} declares neither 'paths' nor 'compose'")
    if compose and len(compose) < 2:
        raise SpecError(f"payload binding {slot!r} 'compose' needs at least two fields")
    return PayloadBinding(slot=slot, paths=paths, compose=compose)


def _policy(raw: dict) -> CallPolicy:
    counters = ("max_asks_per_slot", "max_consecutive_holds", "max_identity_asks", "max_consent_asks")
    for name in counters:
        value = raw.get(name)
        if not isinstance(value, int) or isinstance(value, bool) or value < 1:
            raise SpecError(f"policy {name!r} must be a positive integer, got {value!r}")
    off_script = {
        name: _spoken_line(name, value)
        for name, value in (raw.get("off_script") or {}).items()
        if not name.startswith("_")
    }
    for name in REQUIRED_LINES:
        if name not in off_script:
            raise SpecError(
                f"slot_map.json declares no off-script line {name!r}; the agent has a "
                f"situation it can reach and nothing approved to say in it"
            )
    return CallPolicy(
        max_asks_per_slot=raw["max_asks_per_slot"],
        max_consecutive_holds=raw["max_consecutive_holds"],
        max_identity_asks=raw["max_identity_asks"],
        max_consent_asks=raw["max_consent_asks"],
        off_script=off_script,
    )


def _spoken_line(name: str, value: object) -> SpokenLine:
    if isinstance(value, str):
        text, goal = value, ""
    elif isinstance(value, dict):
        text, goal = str(value.get("line") or ""), str(value.get("goal") or "")
    else:
        raise SpecError(f"off-script line {name!r} must be a string or an object with 'line'")
    if not text.strip():
        raise SpecError(f"off-script line {name!r} is empty; the agent would fall silent")
    if isinstance(value, dict) and "goal" in value and not goal.strip():
        raise SpecError(
            f"off-script line {name!r} declares an empty goal; drop it to speak the line as written"
        )
    if name in VERBATIM_ONLY_LINES and goal:
        raise SpecError(
            f"off-script line {name!r} declares a goal, but this line must be spoken exactly as "
            f"written — what it promises the member is not the agent's to paraphrase"
        )
    return SpokenLine(name=name, line=text.strip(), goal=goal.strip())


# ── validation ───────────────────────────────────────────────────────────


def _validate_required_kinds(spec: SurveySpec) -> None:
    for kind in sorted(SINGLETON_KINDS):
        found = [turn for turn in spec.turns if turn.kind == kind]
        if len(found) != 1:
            raise SpecError(
                f"the script must contain exactly one {kind!r} turn, found {len(found)}"
                f"{': ' + ', '.join(t.node for t in found) if found else ''}"
            )
    if not spec.questions:
        raise SpecError("the script contains no questions")


def _validate_goals(spec: SurveySpec) -> None:
    for turn in spec.agent_turns:
        if not turn.goal.strip():
            raise SpecError(f"turn {turn.node!r} is spoken but has no goal in slot_map.json")


def _validate_slots(spec: SurveySpec) -> None:
    """Declared slots and used slots must be the same set.

    A slot a turn fills but nothing declares would fall through the type system
    with no normaliser and no criticality; a declared slot nothing fills is dead
    weight that misleads the next reader into thinking it is collected.
    """
    used = spec.all_slots() | {slot for turn in spec.turns for slot in turn.payload_slots}
    declared = set(spec.slots)
    undeclared = sorted(used - declared)
    if undeclared:
        raise SpecError(f"the script fills slot(s) with no declaration in slot_map.json: {undeclared}")
    orphans = sorted(declared - used - set(spec.payload_only_slots))
    if orphans:
        raise SpecError(
            f"slot_map.json declares slot(s) no turn fills and that are not payload_only: {orphans}"
        )


def _validate_payload_only(spec: SurveySpec) -> None:
    for name in spec.payload_only_slots:
        if name in spec.all_slots():
            raise SpecError(f"slot {name!r} is payload_only but a question asks for it")
        if name not in spec.payload:
            raise SpecError(f"slot {name!r} is payload_only but slot_map.json binds no payload path for it")


def _validate_choices(spec: SurveySpec) -> None:
    for name, declared in spec.slots.items():
        if declared.type is not SlotType.CHOICE:
            if declared.options:
                raise SpecError(f"slot {name!r} is {declared.type.value} but declares answer options")
            continue
        if len(declared.options) < 2:
            raise SpecError(f"choice slot {name!r} declares fewer than two options")
        values = declared.option_values
        if len(set(values)) != len(values):
            raise SpecError(f"choice slot {name!r} declares duplicate option values: {sorted(values)}")


def _validate_printed_options(spec: SurveySpec) -> None:
    """What the agent accepts must be what the document prints.

    This is the drift check that matters most. Options live in two files — the
    labels in the transcription, the recorded values in the slot map — and a
    survey whose accepted answers have quietly diverged from its printed answers
    produces data that looks clean and means something else.
    """
    for turn in spec.questions:
        if not turn.slots:
            continue
        declared = spec.slot(turn.slot)
        if declared.type is SlotType.CHOICE:
            if tuple(turn.options) != declared.option_labels:
                raise SpecError(
                    f"question {turn.node!r} prints options {list(turn.options)} but slot "
                    f"{turn.slot!r} declares {list(declared.option_labels)}"
                )
        elif declared.type is SlotType.YES_NO and turn.options and tuple(turn.options) != ("Yes", "No"):
            raise SpecError(
                f"question {turn.node!r} fills yes/no slot"
                f"{turn.slot!r} but prints options {list(turn.options)}"
            )


def _validate_one_question_per_slot(spec: SurveySpec) -> None:
    for slot in spec.question_slots:
        asking = [turn.node for turn in spec.questions if slot in turn.slots]
        if len(asking) > 1:
            raise SpecError(f"slot {slot!r} is asked for by more than one question: {asking}")
    for name, declared in spec.slots.items():
        if declared.critical and spec.question_for(name) is None:
            raise SpecError(f"slot {name!r} is critical but no question asks for it")


def _validate_conditions(spec: SurveySpec) -> None:
    """A condition must be answerable at the point the question is reached.

    A question gated on an answer the call has not collected yet can never fire:
    the planner walks the script in order, so the gating question has to come
    first. Getting this wrong silently drops a question from every call.
    """
    asked_by_now: set[str] = set()
    for turn in spec.questions:
        condition = turn.when
        if condition is not None:
            target = spec.slots.get(condition.slot)
            if target is None:
                raise SpecError(
                    f"question {turn.node!r} is conditional on undeclared slot {condition.slot!r}"
                )
            if condition.source == "answer":
                if condition.slot not in asked_by_now:
                    raise SpecError(
                        f"question {turn.node!r} is conditional on {condition.slot!r}, "
                        f"which no earlier question fills"
                    )
            elif not target.payload_only:
                raise SpecError(
                    f"question {turn.node!r} reads {condition.slot!r} from the payload, "
                    f"but that slot is not payload_only"
                )
            wanted = (condition.equals,) if condition.equals else condition.accepted
            allowed = target.option_values if target.type is SlotType.CHOICE else ("yes", "no")
            unknown = [value for value in wanted if value not in allowed]
            if unknown:
                raise SpecError(
                    f"question {turn.node!r} tests {condition.slot!r} against {unknown}, "
                    f"which is not among {list(allowed)}"
                )
        asked_by_now |= set(turn.slots)


def _schema_declares(schema: dict, path: str) -> bool:
    properties = schema.get("properties") or {}
    if "." not in path:
        return path in properties
    section, field_name = path.split(".", 1)
    section_schema = properties.get(section)
    if not isinstance(section_schema, dict):
        return False
    return field_name in (section_schema.get("properties") or {})


def _validate_payload_bindings(spec: SurveySpec, schema: dict) -> None:
    for slot, binding in spec.payload.items():
        if slot not in spec.slots:
            raise SpecError(f"slot_map.json binds a payload path for undeclared slot {slot!r}")
        for path in (*binding.paths, *binding.compose):
            if not _schema_declares(schema, path):
                raise SpecError(
                    f"payload binding {slot!r} reads {path!r},which {INPUT_SCHEMA_FILE.name} does not declare"
                )
    spoken = {slot for turn in spec.turns for slot in turn.payload_slots}
    unbound = sorted(spoken - set(spec.payload))
    if unbound:
        raise SpecError(
            f"the script speaks {unbound} from the work item, but no payload path is bound for them"
        )


def _validate(spec: SurveySpec, schema: dict) -> None:
    _validate_required_kinds(spec)
    _validate_goals(spec)
    _validate_slots(spec)
    _validate_payload_only(spec)
    _validate_choices(spec)
    _validate_printed_options(spec)
    _validate_one_question_per_slot(spec)
    _validate_conditions(spec)
    _validate_payload_bindings(spec, schema)


# ── loading ──────────────────────────────────────────────────────────────


def build_spec(raw: dict, schema: dict) -> SurveySpec:
    """Build and validate a spec from already-parsed JSON. Raises SpecError."""
    for section in ("turns", "slots", "payload", "policy"):
        if section not in raw:
            raise SpecError(f"{SPEC_FILE.name} is missing the {section!r} section")
    spec = SurveySpec(
        source=dict(raw.get("source") or {}),
        turns=tuple(_turn(item) for item in raw["turns"]),
        slots={name: _slot_spec(name, value) for name, value in raw["slots"].items()},
        payload={slot: _payload_binding(slot, value) for slot, value in raw["payload"].items()},
        policy=_policy(raw["policy"]),
    )
    _validate(spec, schema)
    return spec


@lru_cache(maxsize=1)
def load_spec(path: str | None = None) -> SurveySpec:
    raw = json.loads(Path(path or SPEC_FILE).read_text(encoding="utf-8"))
    schema = json.loads(INPUT_SCHEMA_FILE.read_text(encoding="utf-8"))
    return build_spec(raw, schema)


@lru_cache(maxsize=1)
def load_input_schema() -> dict:
    return json.loads(INPUT_SCHEMA_FILE.read_text(encoding="utf-8"))
